# Site settings

title: New Hampshire Radiology Society
# To merge to another URL, replace here:
url: "https://nh-radiology.github.io"
baseurl: ""

theme-home: theme-home-builtin-3.html

rouge-theme: igorpro

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

